#ifndef SETTINGS_H_
#define SETTINGS_H_

#include "stdint.h"

#define SETTINGS_SLA_AMOUNT 8
#define SETTINGS_MODE_AMOUNT 3
#define SETTINGS_MODIFIER_AMOUNT 1
#define SETTINGS_PRESET_AMOUNT 10
#define SETTINGS_PARAMETER_AMOUNT 6
#define SETTINGS_SYSTEMSETTINGS_AMOUNT 12

#define SETTINGS_SLA_INDEX_MAX (SETTINGS_SLA_AMOUNT - 1)
#define SETTINGS_MODE_INDEX_MAX (SETTINGS_MODE_AMOUNT - 1)
#define SETTINGS_MODIFIER_INDEX_MAX (SETTINGS_MODE_INDEX_MAX + SETTINGS_SLA_INDEX_MAX)
#define SETTINGS_PRESET_INDEX_MAX (SETTINGS_MODIFIER_INDEX_MAX + SETTINGS_PRESET_AMOUNT)
#define SETTINGS_PARAMETER_INDEX_MAX (SETTINGS_PARAMETER_AMOUNT - 1)

#define SETTINGS_SLA_LENGTH_MAX 300

#define SETTINGS_SLA0_LENGTH 30
#define SETTINGS_SLA1_LENGTH 300
#define SETTINGS_SLA2_LENGTH 0
#define SETTINGS_SLA3_LENGTH 0
#define SETTINGS_SLA4_LENGTH 0
#define SETTINGS_SLA5_LENGTH 0
#define SETTINGS_SLA6_LENGTH 0
#define SETTINGS_SLA7_LENGTH 0

#define SETTINGS_SLA0_ENABLE 1
#define SETTINGS_SLA1_ENABLE 1
#define SETTINGS_SLA2_ENABLE 0
#define SETTINGS_SLA3_ENABLE 0
#define SETTINGS_SLA4_ENABLE 0
#define SETTINGS_SLA5_ENABLE 0
#define SETTINGS_SLA6_ENABLE 0
#define SETTINGS_SLA7_ENABLE 0

typedef struct{
uint16_t uiSLALength;

uint8_t uiModeParameter[1+SETTINGS_MODIFIER_AMOUNT][SETTINGS_PARAMETER_AMOUNT];
uint8_t uiModeActive[1+SETTINGS_MODIFIER_AMOUNT];

//variables for for example SLA individual time behavior
uint16_t uiModeActors[2];
}tsSettingsStruct;

tsSettingsStruct tsSettings[SETTINGS_SLA_AMOUNT];

//Preset 0 is reserved for initial Settings
tsSettingsStruct tsPresets[SETTINGS_PRESET_AMOUNT][SETTINGS_SLA_AMOUNT];

//variable for standard mode parameters
uint8_t uiSettingsParameterStandard[SETTINGS_MODE_AMOUNT+SETTINGS_MODIFIER_AMOUNT][SETTINGS_PARAMETER_AMOUNT];
void vSettingsInit(void);

#endif /* SETTINGS_H_ */
