#ifndef SETTINGS_H_
#define SETTINGS_H_

#include "stdint.h"

#define SETTINGS_SLA_AMOUNT 8
#define SETTINGS_SLA_INDEX_MAX (SETTINGS_SLA_AMOUNT - 1)

#define SETTINGS_SLA_LENGTH_MAX 300

#define SETTINGS_SLA0_LENGTH 300
#define SETTINGS_SLA1_LENGTH 300
#define SETTINGS_SLA2_LENGTH 300
#define SETTINGS_SLA3_LENGTH 300
#define SETTINGS_SLA4_LENGTH 300
#define SETTINGS_SLA5_LENGTH 300
#define SETTINGS_SLA6_LENGTH 300
#define SETTINGS_SLA7_LENGTH 300

#define SETTINGS_SLA0_ENABLE 1
#define SETTINGS_SLA1_ENABLE 1
#define SETTINGS_SLA2_ENABLE 1
#define SETTINGS_SLA3_ENABLE 1
#define SETTINGS_SLA4_ENABLE 1
#define SETTINGS_SLA5_ENABLE 1
#define SETTINGS_SLA6_ENABLE 1
#define SETTINGS_SLA7_ENABLE 1

typedef struct{
uint16_t uiSLALength;

}tsSettingsStruct;

tsSettingsStruct tsSettings[SETTINGS_SLA_AMOUNT];

void vSettingsInit(void);

#endif /* SETTINGS_H_ */
